# Generated by Django 4.2.8 on 2025-06-28 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alloggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('posizione', models.CharField(max_length=500)),
                ('prezzo_notte', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_ospiti_max', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('numero_camere', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('numero_bagni', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('servizi', models.JSONField(blank=True, default=list)),
                ('disponibile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alloggio',
                'verbose_name_plural': 'Alloggi',
                'db_table': 'alloggi',
                'db_table_comment': 'Tabella degli alloggi disponibili per prenotazione',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoAlloggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('ordine', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alloggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='api.alloggio')),
            ],
            options={
                'verbose_name': 'Foto Alloggio',
                'verbose_name_plural': 'Foto Alloggi',
                'db_table': 'foto_alloggi',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
