# Generated by Django 4.2.8 on 2025-07-13 16:37

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoalloggio',
            name='altezza_originale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotoalloggio',
            name='immagine',
            field=models.ImageField(blank=True, help_text="Upload di un'immagine locale (max 10MB, formati: jpg, jpeg, png, webp)", null=True, upload_to=api.models.foto_alloggio_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), api.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='fotoalloggio',
            name='larghezza_originale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotoalloggio',
            name='tipo',
            field=models.CharField(choices=[('principale', 'Immagine Principale'), ('camera', 'Camera'), ('bagno', 'Bagno'), ('cucina', 'Cucina'), ('esterno', 'Esterno'), ('altro', 'Altro')], default='altro', max_length=20),
        ),
        migrations.AddField(
            model_name='fotoalloggio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fotoalloggio',
            name='ordine',
            field=models.IntegerField(default=0, help_text='Ordine di visualizzazione (0 = immagine principale)'),
        ),
        migrations.AlterField(
            model_name='fotoalloggio',
            name='url',
            field=models.URLField(blank=True, help_text="URL esterno dell'immagine (alternativo all'upload)", max_length=500),
        ),
        migrations.AddConstraint(
            model_name='fotoalloggio',
            constraint=models.CheckConstraint(check=models.Q(('immagine__isnull', False), ('url__isnull', False), _connector='OR'), name='foto_alloggio_immagine_or_url_required'),
        ),
    ]
