# Generated by Django 4.2.8 on 2025-07-17 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fotoalloggio_altezza_originale_fotoalloggio_immagine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('numero_ospiti', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('ospite_nome', models.CharField(max_length=255)),
                ('ospite_email', models.EmailField(max_length=254)),
                ('ospite_telefono', models.CharField(blank=True, max_length=20)),
                ('stato', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFERMATA', 'Confermata'), ('PAGATA', 'Pagata'), ('COMPLETATA', 'Completata'), ('CANCELLATA', 'Cancellata'), ('RIFIUTATA', 'Rifiutata')], default='PENDENTE', max_length=15)),
                ('numero_notti', models.IntegerField(editable=False)),
                ('prezzo_totale', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('note_cliente', models.TextField(blank=True)),
                ('note_interne', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alloggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='api.alloggio')),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
                'db_table': 'prenotazioni',
                'db_table_comment': 'Tabella delle prenotazioni degli alloggi',
                'ordering': ['-created_at'],
            },
        ),
    ]
