version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: >
      sh -c "
        # Attendi che i permessi siano corretti prima di procedere
        until chown -R portale:portale /app/static /app/media /app/logs; do
          echo 'Waiting for volumes to be ready...'
          sleep 2
        done &&

        echo 'Waiting for database...'
        while ! nc -z db 5432; do sleep 1; done
        echo 'Database ready!' &&

        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
      - CREATE_SUPERUSER=true

  frontend:
    command: npm start
    environment:
      - NODE_ENV=development

  nginx:
    ports:
      - "80:80"
      - "443:443"