# Contenuto PULITO E DEFINITIVO per lo sviluppo
version: '3.8'

services:
  backend:
    env_file: .env
    # Sovrascrive il CMD del Dockerfile per usare il server di sviluppo di Django
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Database ready!' &&

        python manage.py migrate &&
        python manage.py create_superuser &&
        python manage.py collectstatic --noinput --clear &&

        echo 'Starting dev server...' &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles # Necessario se collectstatic è eseguito
      - media_volume:/app/media # <--- AGGIUNTO: per persistenza media in sviluppo
      - django_logs:/app/logs # Per i log persistenti in sviluppo 
    environment:
      # Variabili d'ambiente per la configurazione email
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_USE_TLS: "False" # Per Mailhog, non usiamo TLS
      EMAIL_HOST_USER: "" # Mailhog non richiede utente
      EMAIL_HOST_PASSWORD: "" # Mailhog non richiede password
      DEFAULT_FROM_EMAIL: "noreply@portale.local"
      ADMIN_EMAIL: "gartiro@yahoo.it" # L'email dell'amministratore
    depends_on:
      - db
      - mailhog # Aggiungi la dipendenza da mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: portale_mailhog
    logging:
      driver: 'none'
    ports:
      - "8025:8025"  # Interfaccia web
      - "1025:1025"  # SMTP
    networks:
      - backend-network

  frontend:
    # Sovrascrive il CMD del Dockerfile per usare il server di sviluppo di React
    command: npm start
    environment:
      # Fix WebSocket per hot-reload attraverso nginx SSL
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=443
      - WDS_SOCKET_PATH=/ws
      - HTTPS=true
      - WDS_SOCKET_PROTOCOL=wss
  
  nginx:
    # USA LA CONFIGURAZIONE DI SVILUPPO
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - nginx_logs:/var/log/nginx