# Contenuto PULITO E DEFINITIVO per lo sviluppo
version: '3.8'

services:
  backend:
    # Sovrascrive il CMD del Dockerfile per usare il server di sviluppo di Django
    command: python manage.py runserver 0.0.0.0:8000
    
  frontend:
    # Sovrascrive il CMD del Dockerfile per usare il server di sviluppo di React
    command: npm start
    environment:
      # Fix WebSocket per hot-reload attraverso nginx SSL
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=443
      - WDS_SOCKET_PATH=/ws
      - HTTPS=true
      - WDS_SOCKET_PROTOCOL=wss
  
  nginx:
    # USA LA CONFIGURAZIONE DI SVILUPPO
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - nginx_logs:/var/log/nginx